### PR TITLE
Add mail headers for attachments and filename

### PR DESCRIPTION
**Pull request by kadogo**
Hello,
Like said on reddit here is the PR ^^

I kept the content-type that can be empty but it didn't happen in my test yet.
For the filename I thought it could be nice to use their ID when there are no filename and it looks not too bad.
For having the extension I used ´strrchr´ maybe there is a better way to do it but it's the one I found when I was lookin for having a substring.

For my test after that the eml were generated I just did `base64 attachment >> file.eml` and it was working so I think it just need the decypted file and encode it in base64 and that the part I was lost.

Feel free to adapt or change anything if needed.
Cheers

### CODE REVIEW

**Comment by tbvdm** [comment]
Thanks! This looks like a good start. I'll look into how best to get the attachment data and base64-encode it.

**Comment by kadogo** [comment]
Yes I did few copy paste for making it work and few stuff can be weird.

Some attachments are pictures with .jpg but the content type is jpeg so in the mail it's converted in .jpeg instead of .jpg. I not think it's a big deal but it can be weird ^^

**Comment by tbvdm** [comment]
I just pushed code to support attachments in maildirs. Please give it a try. I'd be interested to know which mail client(s) you used to view the maildirs with. Thanks!

**Comment by kadogo** [comment]
At first view it look pretty good.

I'm using thunderbird with the extension ImportExportToolsNG.

I add ".eml" to the files with rename

```
rename 's/$/.eml/g' ./cur/*
```

And I import all the files.

Now maybe see how much it's needed to be changed or not but I think that it would be better to make subfolder with the receiver name so we keep a view like in signal, but that can be better be achieved with thunderbird filters maybe?

I saw that attachment get the name "Partie X" (in French), it's not a big deal on his own but maybe the id would look better with the extension at end in case we want to export?

But it works already and that is already very good ^^

Edit:
Little update, I was testing only on a thread but on my whole backup I got "sigbak: Cannot get messages: Cannot find attachment file" and the check work without any issue. Is there a way to  give you few more info? I think it's something like the previous commit so unrelated to the maildir attachment.

**Comment by tbvdm** [comment]
> Now maybe see how much it's needed to be changed or not but I think that it would be better to make subfolder with the receiver name so we keep a view like in signal, but that can be better be achieved with thunderbird filters maybe?

That's a good idea. Note that you can already do this with the -t option, but you'd have to export each conversation thread separately. Which is not ideal. I'll think about adding an option to specify that each conversation should go into a separate maildir.

> I saw that attachment get the name "Partie X" (in French), it's not a big deal on his own but maybe the id would look better with the extension at end in case we want to export?

Ah yes, I have left out attachment filenames for now. They may contain characters that need to be encoded, but I haven't got round to that yet.

**Comment by tbvdm** [comment]
I just saw your edit with the "Cannot find attachment file" error. Have you ever deleted an attachment in the Signal app (maybe to save space, for example)?

**Comment by tbvdm** [comment]
Alternatively, have you ever sent or received a view-once message?

**Comment by kadogo** [comment]
Sorry I just checked my emails

I think I only have the remove scenario in this backup but if you want in the next one I will have the one time view too if it can be usefull ^^

For the filename I had used the attachement id when att->filename was empty I think it's pretty safe because that looks like only digit but maybe there is a better way to name them.

The thread option could be usefull because I think just drag and drop work too (not sure we really need thunderbird extension)

**Comment by tbvdm** [comment]
> I think I only have the remove scenario in this backup but if you want in the next one I will have the one time view too if it can be usefull ^^

I thought it was possible to delete an attachment from a message without deleting the message itself, but I'm unable to do it. A quick web search seems to indicate that this isn't possible in Signal.

Could you tell me if your remove scenario removed only the attachment or the complete message? If you still remember, could you tell me what steps you took?

> For the filename I had used the attachement id when att->filename was empty I think it's pretty safe because that looks like only digit but maybe there is a better way to name them.

Right. I hadn't really decided how to handle missing filenames, but I guess there's no reason not to use the attachment id for now.

**Comment by kadogo** [comment]
I did a fast test on signal-desktop for "my own notes" and it looks like the "message display" stay there but is replaced by "this message was removed".

For the attachment like a picture the whole message is removed and no longer exist

**Comment by tbvdm** [comment]
Great, thanks. I think the best way is to add some debug output which hopefully will provide some clues. I'll let you know when I have something that you could try.

**Comment by kadogo** [comment]
Sure no problem ^^

**Comment by tbvdm** [comment]
Here's the first attempt. Please run the following:

$ git pull
$ git checkout test
$ make clean
$ make
$ ./sigbak messages signal.backup msg 2>debug

The "debug" file will contain lines similar to this one:

sigbak: file missing for attachment 12-345 in message 1-678

Note that "12-345" is the attachment id, and "1-678" is the message id.

For every line, please do the following:

- Look up the message in the "msg" file. Search for the message id to locate the message.
- Does the message give you any hints or clues as to why the attachment might be missing?
- If not, please look up the message in your Signal app. Can you see the missing attachment there? Does it give you any other clues?

Finally, please also run this command:

$ ./sigbak attachments signal.backup att

This will export all attachments to the "att" directory. Each attachment is named after its attachment id. Please see if you can find the missing attachments (please check all attachments if you can!). If you can find a missing attachment, do the attachment ids match?

Let me know if something isn't clear or if you can't get it to work. Thanks!

**Comment by kadogo** [comment]
When I try to use `./sigbak messages signal.backup msg 2>debug` I got a segmentation error.
Not sure what I can do to help trying to debug the segmentation error.

```
~/.local/bin/sigbak messages ~//signal-2021-04-11-23-11-49.backup 2>debug
Enter 30-digit passphrase (spaces are ignored): 
Erreur de segmentation
```

**Comment by tbvdm** [comment]
> When I try to use `./sigbak messages signal.backup msg 2>debug` I got a segmentation error.

My mistake, pardonnez-moi. :) Please try again:

$ git pull
$ make clean all
$ ./sigbak ...

> ~/.local/bin/sigbak messages ~//signal-2021-04-11-23-11-49.backup 2>debug

You forgot the "msg" file argument in that command!

**Comment by kadogo** [comment]
I went a bit further.

It looks like it's a picture in a group but if I just ls the attachement id I not see it in the attachement dump so I wanted to check all the attachment for the thread to see if I have the attachment further or not but I'm not so far yet.

At first view anyway I attachment is not deleted but the message after this one is deleted with a "message removed" in my desktop signal.

Not sure if it help I will check further in the evening.

**Comment by tbvdm** [comment]
Thanks. If checking the attachments is taking too much time, then forget about it. I wouldn't want you to spend your whole evening on it.

Meanwhile, could you answer a few other questions?

- Could you confirm that you have found the message in your Signal app, that the missing attachment is a picture and that this picture is visible in your Signal app (i.e. there doesn't appear to be anything wrong with the attachment in the Signal app)?

- Could you describe the message in as much detail as you're comfortable with? Is it a quoted message? How many attachments does it have? Anything that sets it apart from a regular message is interesting to know.

- When was the message sent? (I'd like to know if it's an older or a newer message.)

- What is the date of the backup?

- Do you have other backups? If so, could you find out if those other backups have the same problem? Or perhaps other backups have *other* messages with *other* missing attachments? (If you don't have other backups, could you create a new one and check that?)

- How many missing attachment files are reported in the "debug" file?

- Could you tell me the version of the database in the backup? To find out, please run this command:
$ sigbak dump signal.backup | grep -A1 DatabaseVersion
The database version is a 2-digit number at the end of the second line.

- Finally, you wrote that it's a group message. If possible, could you maybe check a backup from another group member?

A lot of questions, sorry about that. I'm more or less wildly guessing at this stage. Feel free to skip questions that take too much time. Thanks again!

**Comment by kadogo** [comment]
No issue, I will answer a part now and the rest later based on what is needed ^^

> - Could you confirm that you have found the message in your Signal app, that the missing attachment is a picture and that this picture is visible in your Signal app (i.e. there doesn't appear to be anything wrong with the attachment in the Signal app)?

I think the rest would not be needed I fill the rest as I can still in case. By checking it on my signal app (on phone) I cannot display the picture. The display is there but i cannot see or save it. If I try to save it, it say that the file got an error in memory. It looks like it's corrupted maybe because I'm short on space on my phone and just bad luck ^^

> - Could you describe the message in as much detail as you're comfortable with? Is it a quoted message? How many attachments does it have? Anything that sets it apart from a regular message is interesting to know.

> - When was the message sent? (I'd like to know if it's an older or a newer message.)

```
From: XXX
Sent: Thu, 18 Mar 2021 22:35:30 +0100
Received: Thu, 18 Mar 2021 22:35:34 +0100
Thread: 192
Message id: 1-7185
Attachment: no filename (image/jpeg, 42070 bytes, id 5030-1616103334477)
Reaction: 😂 from YYY
Reaction: 😂 from ZZZ
```

I set the whole message above and just hide some value, it's a picture with 2 reactions.

> - What is the date of the backup?

2021-04-11-23-11-49 is what content the filename backup

> - Do you have other backups? If so, could you find out if those other backups have the same problem? Or perhaps other backups have *other* messages with *other* missing attachments? (If you don't have other backups, could you create a new one and check that?)

I not have others right now but I can make one and try with this one if it can help

> - How many missing attachment files are reported in the "debug" file?

Only one 

> - Could you tell me the version of the database in the backup?

```
	version (DatabaseVersion):
		version (uint32): 90
```

> - Finally, you wrote that it's a group message. If possible, could you maybe check a backup from another group member?

I not have other groups but I can make one and just sending message myself maybe it would be good?

**Comment by kadogo** [comment]
The issue is if it's corrupted like I think I'm not sure there is a way to check that, maybe in the database it would show something else?

**Comment by tbvdm** [comment]
kadogo (2021-04-28 10:00 -0700):
> I think the rest would not be needed I fill the rest as I can still in case. By checking it on my signal app (on phone) I cannot display the picture. The display is there but i cannot see or save it. If I try to save it, it say that the file got an error in memory. It looks like it's corrupted maybe because I'm short on space on my phone and just bad luck ^^

Thanks, that's very helpful (but I'm sorry to hear your picture is corrupted). I think that explains the issue, then. An attachment file stored on your phone got corrupted and therefore could not be included in the backup.

If you want to be sure about this, you could create a new backup and then take a look at the Android log (if you know how to do that). If Signal fails to include an attachment in the backup, it should warn about this in the Android log.

As far as I know, there's no way for sigbak to detect this condition (in the database or otherwise), so I think the only thing sigbak can do is not to error out on missing attachments (and print a warning instead). I'll commit that change soon.

Thanks once again. :)

**Comment by kadogo** [comment]
Welcome I think it would be the best (maybe display the whole message could help to check too if there is an issue).

No issue if I really want I still got it on the desktop and it was not an important picture ^^
A question a bit out of the scope but I guess that sigbak could als work on the desktop database maybe?

**Comment by tbvdm** [comment]
> Welcome I think it would be the best (maybe display the whole message could help to check too if there is an issue).
 
True, sigbak should provide a little more detail when it reports errors or warnings. 

> No issue if I really want I still got it on the desktop and it was not an important picture ^^

Ah, good. :)

> A question a bit out of the scope but I guess that sigbak could als work on the desktop database maybe?

It's not so simple, unfortunately. However, I am writing another utility to export data from Signal Desktop: https://github.com/tbvdm/sigtop . It would be interesting to unify sigbak and sigtop into a single utility one day. But it'll take time.

**Comment by kadogo** [comment]
About the warning and errors I think the msg output is really usefull with the ID because at end you can extract the messages from a thread and just try to find a corresponding with the signal app.

Ah I didn't know about sigtop, I bookmark I'm sure it will come in handy when by bad manipulation peoples remove signal from the phone and reinstall it and seeing everything is gone.

When you have an update don't hesitate to ping me back here I will try one more time with the warning and everything ^^

**Comment by tbvdm** [comment]
Sure, I'll let you know. :) By the way, if you're still on the test branch, don't forget to switch back to portable.

**Comment by tbvdm** [comment]
Hi, I just pushed a number of commits that should address some of the things we discussed here. If you run into problems, let me know!

**Comment by kadogo** [comment]
Hi, thanks I will give it a try in the next days. If not it will be in the weekend ^^

**Comment by kadogo** [comment]
Hello @tbvdm 

Sorry for the time before I tested it back

I used the same backup but I got many 

```
sigbak: fopen: ./backup//cur/XXX.XXX.localhost:2,S: File exists
```

And also `sigbak: Attachment not available in backup` but these one are maybe normal.

Is it possible to maybe get the message id of the message when there is an attachment missing in that way it's always possible to use the text format to check it back.

The fopen error look a bit weird so I didn't check further for now

**Comment by tbvdm** [comment]
> I used the same backup but I got many 
> 
> ```
> sigbak: fopen: ./backup//cur/XXX.XXX.localhost:2,S: File exists
> ```

This error would imply that there are two messages that were sent at the same time *and* received at the same time. I suppose it's not impossible for this to happen. However, you write that you get many of these errors. That is surprising.

I need more information, so I'd like you to run a few commands. It would be helpful for me to know the sent time and received time for a number of messages, but I don't know if you are willing to disclose that information. You could send that information directly to me if you prefer (via email for example). But if you're not comfortable with this, we could try something else, so no worries. Let me know.

> And also `sigbak: Attachment not available in backup` but these one are maybe normal.
> 
> Is it possible to maybe get the message id of the message when there is an attachment missing in that way it's always possible to use the text format to check it back.

It turns out you get two warnings for each missing attachment. One warning includes the attachment id, the other warning doesn't. I'll remove the warning without the attachment id. You can use the attachment id to look up the message in the text output format.

**Comment by kadogo** [comment]
Hello, by email would be good but if it's easier here it's ok too.

I not think the time for the message would be a big deal don't worry ^^

**Comment by tbvdm** [comment]
Good. First, please paste the output of the following command:

```
./sigbak messages -f maildir signal.backup maildir 2>&1 | grep fopen
```

Next, run this:

```
./sigbak sqlite signal.backup signal.db
```

Ensure you have installed the sqlite3 utility and then paste the output of the following command:

```
sqlite3 signal.db 'SELECT sent, recv, COUNT(*) AS n FROM (SELECT date_sent AS sent, date AS recv FROM sms UNION ALL SELECT date AS sent, date_received AS recv FROM mms) GROUP BY sent, recv HAVING n > 1'
```

I don't know how many lines of output these commands will produce. If it's too long, then maybe instead of pasting you should redirect the output to files and attach those here.

**Comment by tbvdm** [comment]
Good. First, please paste the output of the following command:

$ ./sigbak messages -f maildir signal.backup maildir 2>&1 | grep fopen

Next, run this:

$ ./sigbak sqlite signal.backup signal.db

Ensure you have installed the sqlite3 utility and then paste the output of the following command (it's a single command, all on one line):

$ sqlite3 signal.db 'SELECT sent, recv, COUNT(*) AS n FROM (SELECT date_sent AS sent, date AS recv FROM sms UNION ALL SELECT date AS sent, date_received AS recv FROM mms) GROUP BY sent, recv HAVING n > 1'

**Comment by kadogo** [comment]
Hello I did the commands but it's true that it's .. it's long I must redirect too a file to give you an idea ^^

As teasing  ^^

```
$ wc -l fopen.txt 
2761 fopen.txt
$ wc -l sql.txt 
2584 sql.txt
```

So if you have a contact mail I send them there it would be better I think, thanks.

**Comment by tbvdm** [comment]
My address is tim kariliq nl (replace the spaces with the right symbols). It might be a good idea to compress the files before you send them. Thanks.

**Comment by kadogo** [comment]
If I didn't make a mistake they are sent.

**Comment by tbvdm** [comment]
Yes, got it. Thanks. I'll have a look.

**Comment by tbvdm** [comment]
Great, thanks. So you do have messages with identical sent times and identical received times. Quite a lot of them. The sent time and received time always are identical, too. And they appear to have a resolution of 1 second instead of 1 ms. The messages were sent between 2012 and 2016. The number of fopen errors matches the number of sent/received duplicates.

In any case, it's clear that sigbak has to generate maildir filenames differently. I'll commit a fix for that.

Still, I'm curious about these messages. Given that they're from 2012-2016, maybe they are imported sms messages. But I don't think that could explain why you have so many with identical sent/received times. Could you look a few of them up? To do so, please run the following commands:

$ mv cmd-messages.c cmd-messages.c.orig
$ sed '/Sent/a\
fprintf(fp, "Sent: %" PRIu64 "\\n", msg->time_sent);
' cmd-messages.c.orig > cmd-messages.c
$ make clean all
$ ./sigbak messages signal.backup msg
$ mv cmd-messages.c.orig cmd-messages.c

In the "msg" file, search for "Sent: 1437146298000". You should have exactly 5 messages with this field. What kind of messages are they? Imported messages, from sms or from another messaging service? Or service/status messages from Signal perhaps (messages notifying you of encryption errors etc.)? Are the message texts of all these 5 messages identical?

Could you do the same for the ones below?

1345555158000 (you should have exactly 2 of these)
1414392491000 (exactly 2)
1437381290000 (exactly 5)
1454087547000 (exactly 3)

Thanks very much.

**Comment by tbvdm** [comment]
> In the "msg" file, search for "Sent: 1437146298000". You should have exactly 5 messages with this field. What kind of messages are they? Imported messages, from sms or from another messaging service? Or service/status messages from Signal perhaps (messages notifying you of encryption errors etc.)? Are the message texts of all these 5 messages identical?

Also, do all these 5 messages have the same sender/recipient?

Thanks again.

**Comment by kadogo** [comment]
Hello

It's kinda weird, for each message they are the same recipient (by number I mean).

1437146298000 it looks like kinda of encryption but I not remember if they are sms or signal messages I knew the recipient before signal and it used after signal too but I not think it woud be encrypted by sms. And the "message" are not the same.

1345555158000 sms import (i not remember i used signal with the recipient) and same messages

1414392491000 sms or signal (it's the same recipient of 1437146298000) maybe but the message are the same 

1437381290000 it's like 1437146298000 same recipient but it looks like encryption and any message is different

1454087547000 it's the same of 1437146298000 and same recipient too

**Comment by tbvdm** [comment]
Great, thanks for your effort. Do you think it's possible that these messages somehow have been imported more than once?

One last question, if you don't mind: do messages with the same time also have consecutive message ids? For example, in the case of 1437146298000, do the message ids of the 5 messages look like 0-123, 0-124, 0-125, 0-126, 0-127; or do they have gaps between them?

**Comment by tbvdm** [comment]
I have just committed a fix for the fopen errors. Please give it a try.

**Comment by kadogo** [comment]
Hello sorry for my response it's a big week so I'm a bit late.

> Great, thanks for your effort. Do you think it's possible that these messages somehow have been imported more than once?

It's possible but I think I would have more duplicate because I keep almost any messages.

> One last question, if you don't mind: do messages with the same time also have consecutive message ids?

You got it right for each duplication the `Message id` are following each others

> I have just committed a fix for the fopen errors. Please give it a try.

I tried again and I no more got fopen errors, thanks ^^
I will take a look about the attachment missing see if they are buggy in my phone too like last time.

We talked before of maybe make "directories" for each send so that in Thunderbird it could really be a way to consult the backup I don't know if you already tought about it or if you prefer that I make another proper issue for that?

**Comment by tbvdm** [comment]
> Hello sorry for my response it's a big week so I'm a bit late.

No worries.

> > Great, thanks for your effort. Do you think it's possible that these messages somehow have been imported more than once?
> 
> It's possible but I think I would have more duplicate because I keep almost any messages.
> 
> > One last question, if you don't mind: do messages with the same time also have consecutive message ids?
> 
> You got it right for each duplication the `Message id` are following each others

Thanks. I think this has to remain a mystery. We could try to investigate further but I'm not sure it'll be worthwhile. The most important thing is that these messages are now handled correctly.

> I will take a look about the attachment missing see if they are buggy in my phone too like last time.

Yes, please do.

> We talked before of maybe make "directories" for each send so that in Thunderbird it could really be a way to consult the backup I don't know if you already tought about it or if you prefer that I make another proper issue for that?

Discussing it here is fine. :) I think this is a useful feature, so I will definitely add it. I'll keep you posted.

**Comment by tbvdm** [comment]
> We talked before of maybe make "directories" for each send so that in Thunderbird it could really be a way to consult the backup I don't know if you already tought about it or if you prefer that I make another proper issue for that?

Hi, it has been quite a while, but I wanted to say that I've added this feature: every conversation will now be exported to a separate maildir.

I'm closing this PR, but if there any issues, let me know. Thanks!

**Comment by kadogo** [comment]
Hello @tbvdm 

Thanks to be honest I didn't retry it yet but I will add that on my to-do list ^^
Thanks again for adding this feature ^^

**Pull request closed without merging**
